import AuthProvider from './context/AuthProvider';
import './globals.scss';
import Providers from './providers';
import 'react-toastify/dist/ReactToastify.css';
export const metadata = {
  title: 'shop 03',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <Providers>{children}</Providers>
        </body>
      </AuthProvider>
    </html>
  )
}
