import './globals.scss';
import './providers'
export const metadata = {
  title: 'shop 03',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

      </body>
    </html>
  )
}
