import Header from "@/Components/Header/Header";
export const metadata = {
     title: 'Profile',
     description: 'Generated by create next app',
}
export default function HomeLayout({ children }) {
     return (
          <>
               <Header />
               <main>
                    {children}
               </main>
          </>

     )
}
